#!/bin/bash
for f in Resources/JS/*.js; do FILES="$FILES $f"; done;

./vendor/UglifyJS2/bin/uglifyjs\
 --wrap=TogglerJS\
 --source-map Resources/JS.min/src.map\
 --compress drop_console,cascade,join_vars,if_return,hoist_funs,hoist_vars,unused,loops,booleans,evaluate,dead_code,comparisons,sequences,drop_debugger,conditionals\
 --mangle\
 -- $FILES > Resources/JS.min/toggler.js;